version: "3"

services:
    dex:
        image: dexidp/dex
        ports:
            - "5556:5556"
        volumes:
            - ${PWD}/dex:/etc/dex
        command:
            - dex serve /etc/dex/config.yaml
